### PR TITLE
Removing Barcelona from 'Who is using CONSUL?'. Fixes #4

### LINKED ISSUE #4: Remove Barcelona from "Who is using CONSUL?"
Since February, Barcelona isn't using Consul, but Decidim, a new version (non compatible) with the architecture that Consul offers. The new framework has been fully rewritten. For clarity and fairness, you should remove Decidim from decide.es list of cities.

* Legacy/Consul version deprecated: https://github.com/AjuntamentdeBarcelona/decidim.barcelona-legacy 
* New version: https://github.com/AjuntamentdeBarcelona/decidim-barcelona
* Decidim framework: https://github.com/decidim/decidim 

There is even a website specific for decidim: http://decidim.org

### PR DESCRIPTION
**Pull request by andreslucena**
Removes BCN from consul use cases. See #4. 

For the future, I think it'd be better if we used some kind of YML for this changes. I had to change all the organizations numbers so it's sorted well. If you prefer to have organization_2 missing let me know and I make another PR. 

Also maybe you should add another use case so the design doesn't break: 
image

### CODE REVIEW

**Comment by andreslucena** [comment]
Hi! Could you review this and let us know something please?

**Comment by xabier** [comment]
This is embarrassing ... can anybody please accept this PR?

**Comment by andreslucena** [comment]
@bertocq could you please check this issue and tell us something?

**Comment by xabier** [comment]
@bertocq @voodoorai2000 @xuanxu please, this is serious, now the PR has conflicts ... it is very hard for us to understand why there is no response for this PR, nor for the Issue #4 that was opened 4 months ago :cry:

**Comment by MariaCheca** [comment]
Hi @xabier!

We are very sorry, but we had to delay this changes because we've been working very hard improving CONSUL and adding new features. Maintaining an open source project and staying in touch with the community around it is not always easy and quick! We hope you understand.

Currently we're working on a new design for the website, and when it's ready we'll include your suggestions.

Thank you for your understanding, have a nice day!

**Comment by xabier** [comment]
Hi @MariaCheca , thanks for your response. Accepting a PR takes 1 second. Whether there is a new website is irrelevant for this issue and the PR that has been waiting for months. I perfectly understand the complexities of maintaining an open source project. Accepting the PR takes less time than writing the response you wrote. We would really appreciate if you could merge it ASAP. Thank you very much in advance and congratulations for your project.

**Comment by MariaCheca** [comment]
Hi @xabier @andreslucena! We're happy to inform you that the changes you requested have been applied in the new version of the CONSUL web.

As you can see in https://github.com/consul/website/blob/master/_includes/organizations.html the Barcelona City Council is not among the cities and organizations using CONSUL anymore. Therefore we'll close this PR and the issue #4 related to it.

Thanks for your suggestion and lots of luck with your project!

**Comment by xabier** [comment]
@MariaCheca congratulations, the new site looks cool!

**Pull request closed without merging**
